[tools]
# Runtime
node = "latest"
uv = "latest"

# Project
opentofu = "latest"
terragrunt = "latest"
just = "latest"
lefthook = "latest"

# Lint / format
actionlint = "latest"
editorconfig-checker = "latest"
shellcheck = "latest"
yamlfmt = "latest"
yamllint = "latest"
"npm:@commitlint/cli" = "latest"
"npm:markdownlint-cli" = "latest"
