---
creation_rules:
  # Terraform State
  - path_regex: \.tfstate$
    encrypted_regex: "^(.*)$" # Encrypt the entire file
    key_groups:
      - age: [age1r8r24rkk237kr59xd2ztk258c9und3vkradrv2q38qtw0asn3awsnw2g0r]

  # Terraform Credentials
  - path_regex: \.tfvars$
    encrypted_regex: "^(.*)$" # Encrypt the entire file
    key_groups:
      - age: [age1r8r24rkk237kr59xd2ztk258c9und3vkradrv2q38qtw0asn3awsnw2g0r]
