# dotrepos:begin .yamllint.yaml@6dad6f3f42174d899d3c3624132cc3c569b0b509
---
extends: default
ignore: |
  .git/
  .github/workflows/
  .forgejo/workflows/
  node_modules/
  venv/
  target/
  .direnv/
  .terragrunt-cache/
  # dotrepos:slot extra-ignore
rules:
  indentation:
    spaces: 2
    indent-sequences: whatever
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  truthy:
    check-keys: false
  octal-values:
    forbid-implicit-octal: true
# dotrepos:end
