# dotrepos:begin .yamlfmt.yaml@6dad6f3f42174d899d3c3624132cc3c569b0b509
---
doublestar: true
include:
  - "**/*.yaml"
  - "**/*.yml"
exclude:
  - ".git/**"
  - "target/**"
  - ".direnv/**"
  # dotrepos:slot extra-excludes
formatter:
  type: basic
  disable_alias_key_correction: true
  drop_merge_tag: true
  eof_newline: true
  force_array_style: block
  include_document_start: true
  indentless_arrays: false
  line_ending: lf
  pad_line_comments: 2
  retain_line_breaks: true
  retain_line_breaks_single: true
  scan_folded_as_literal: true
  trim_trailing_whitespace: true
# dotrepos:end
