---
name: Commitlint
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
  push:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install commitlint
        env:
          # renovate: datasource=npm depName=@commitlint/cli
          COMMITLINT_VERSION: "21.0.1"
        run: npm install -g "@commitlint/cli@${COMMITLINT_VERSION}"

      - name: Validate PR Title
        if: github.event_name == 'pull_request'
        run: echo "$PR_TITLE" | commitlint --verbose
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Validate last commit
        if: github.event_name == 'push'
        run: commitlint --last --verbose
