---
name: dotrepos sync
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sync:
    if: contains(github.event.pull_request.labels.*.name, 'dotrepos-sync')
    uses: vrozaksen/dotrepos/.forgejo/workflows/dotrepos-sync.yml@main
    secrets: inherit
