---
name: Terraform
on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
      - modules/**
      - root.hcl
      - "**/.terraform.lock.hcl"
  pull_request:
    paths:
      - infrastructure/**
      - modules/**
      - root.hcl
      - "**/.terraform.lock.hcl"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  fmt:
    uses: vrozaksen/dotrepos/.forgejo/workflows/terraform/fmt.yml@main
  trivy:
    uses: vrozaksen/dotrepos/.forgejo/workflows/terraform/trivy.yml@main
