---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Commitlint
permissions: { contents: read }

on:
  pull_request_target: {}
  push: {}

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup mise
        uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1

      - name: Validate PR Title
        if: github.event_name == 'pull_request_target'
        run: echo "$PR_TITLE" | mise exec -- commitlint --verbose
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Validate last commit
        if: github.event_name == 'push'
        run: mise exec -- commitlint --last --verbose